### ISSUE TITLE
Join a meeting in Googl Meet Error

### ISSUE THREAD

**Issue by splitz-ux** [pi-ra/beesy-issue-tracker#22]
I am logged into a Google meet video call and it won't start recording, I push the button to record and it does nothing pls advise 
<img width="321" alt="Screenshot 2023-09-25 at 9 58 23 AM" src="https://github.com/pi-ra/beesy-issue-tracker/assets/68662065/b6a1af28-f456-409f-b108-176b3076b8eb">

**Comment by rahul-kurup** [comment]
Do you face this issue everytime?

**Comment by splitz-ux** [comment]
its has been happening since I had to reinstall Google Chrome

DIrect -424-226-8278
www.Splitzbymbm.com <http://www.splitzbymbm.com/>

"Managing Royalties one Split at a Time"

**Comment by rahul-kurup** [comment]
As a temporary fix, you may follow

["How to Remove Extension Data from Local Storage in Google Chrome" section](https://www.groovypost.com/howto/clear-local-storage-for-a-website-or-extension-in-google-chrome/)

Close all Google Meet tabs and do this activity

**Comment by piyu-sh** [comment]
Hey @splitz-ux, is it working now after Rahul's suggestion ?
 If not, can you please try reinstalling the extension.

**Comment by rahul-kurup** [comment]
Similar: https://github.com/pi-ra/beesy-issue-tracker/issues/27

**Comment by piyu-sh** [comment]
Hey @splitz-ux , over the last few releases, we've published a number of stability/usability fixes, so does this issue still happen with you on v0.0.14 of Beesy ?

**Comment by splitz-ux** [comment]
No this issue is good to go Thanks
DIrect -424-226-8278
www.Splitzbymbm.com <http://www.splitzbymbm.com/>

"Managing Royalties one Split at a Time"
