### ISSUE TITLE
Retrieve recording 

### ISSUE THREAD

**Issue by ashishsinojia** [pi-ra/beesy-issue-tracker#24]
I have accidentally closed my chrome browser during meeting. How to retrieve recording file? Using MacOS and way to get the file?

**Comment by rahul-kurup** [comment]
Hi. Did you force close the browser or simply clicked X on the title bar?

**Comment by ashishsinojia** [comment]
Accidnek closed the browser. Commad + Q

**Comment by rahul-kurup** [comment]
Unfortunately you won't be able to retrieve the recording as it stays in the memory during the browser session. Ideally once the browser is closed in any manner which does not trigger a proper close procedure for any active website (in this case, Beesy recording tab), all the data in memory would get garbage collected (destroyed).

**Comment by piyu-sh** [comment]
Hey @ashishsinojia, like @rahul-kurup mentioned that you might not be able to retrieve that recording but your comment has got us thinking and we're brainstorming on possible solutions to this problem.
While its possible we might not be able to implement any solution to it considering the complexity, but we're exploring the problem you raised, thanks for that.
