### ISSUE TITLE
A way to retrieve old recordings 

### ISSUE THREAD

**Issue by piyu-sh** [pi-ra/beesy-issue-tracker#25]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

Refer this issue for context : https://github.com/pi-ra/beesy-issue-tracker/issues/24

This feature request might encompass multiple problems where in recordings are kinda lost, and user can't download them:
- if a browser is closed, an active recording might not be downloaded
- a user started downloading a recording, but for some reason it was cancelled/stopped(network issues ?)
- user deleted the recording accidentally and wants to download again
- other possible scenarios

So we need a way to download recorded videos even after there is no ongoing recording.

**Comment by MorpheMedia** [comment]
Is there any update to this? I have just lost a 1h20 recording from a call because my chrome crashed and mac restarted. Is there any way of retrieving this?

**Comment by rahul-kurup** [comment]
Unfortunately, the recording stays within the memory and gets wiped off once a session ends by any means. We are working on a feature to keep track of old recordings for cases like yours, but it's a work in progress.

**Comment by piyu-sh** [comment]
We recently launched v0.0.13 of [Beesy](https://chromewebstore.google.com/detail/beesy-record-google-meets/eabicnldgjknbifdgmnieblkbnggfnde/reviews) with persistent recordings, which means even if your download didn't start for some reason or your browser/system crashed, we still save the recording to the user filesystem.

Here's a quick video on how it works: [video link](https://github.com/pi-ra/beesy-issue-tracker/blob/main/RELEASES.md#v0013--latest--mar-19-2024)

Please give it a try and let us know if it helps !
