### ISSUE TITLE
Extension market page is not accessible from EU

### ISSUE THREAD

**Issue by amano-takahisa** [pi-ra/beesy-issue-tracker#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I was trying to install your beesy chrome extension from google chrome webstore, but it redirected to this page, and not available.
![image](https://github.com/pi-ra/beesy-issue-tracker/assets/51368373/66e6a8fc-bdfc-443e-95c3-d804b12b7bb3)

Do you limit the region where the extension can be installed with some reason?
I was trying to access from EU country, and not accessible, but when I was accessed from Japan via VPN, extension was shown in the webstore. 

### Steps To Reproduce

1. Access [webstore](https://chrome.google.com/webstore/detail/beesy-record-google-meets/eabicnldgjknbifdgmnieblkbnggfnde) from EU country.

### Environment including version

```Markdown
- Beesy: -
- OS: I tried both Arch linux, Windows 11
- Browser: Google chrome
- Media Player: -
```

**Comment by rahul-kurup** [comment]
Hi, the extension is not currently available in EU. It may come in future.
