### ISSUE TITLE
Recording problem with voice pitch and audio cutting in and out

### ISSUE THREAD

**Issue by mrnathanrehm** [pi-ra/beesy-issue-tracker#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

Hey, thanks so much for developing this! I was using it just fine for several weeks. Today when I hit record, it caused the audio of people's voices to go higher in pitch in a funny sounding way, plus the audio would rapidly cut in and out so it sounded robotic. I tried uninstalling, reinstalling, closing the browser, etc. No luck. I am using Brave browser on Windows 11. Hoping it can be fixed if this isn't just a local problem. Thanks!

### Steps To Reproduce

1) Install Beesy to Brave Browser
2) Start Google Meet meeting
3) Start recording via Beesy
4) Someone on the call that is not recording begins speaking

### Environment including version

```Markdown
- Beesy: 0.0.11
- OS: Windows 11
- Browser: Brave
- Media Player: N/A
```

**Comment by piyu-sh** [comment]
Hey @mrnathanrehm , I tried the steps given and recorded a meeting on brave, and it worked normally for me.

Seems like the issue is most probably a local one. Could you please try running this on chrome or edge also?

**Comment by mrnathanrehm** [comment]
> Hey @mrnathanrehm , I tried the steps given and recorded a meeting on brave, and it worked normally for me.
> 
> Seems like the issue is most probably a local one. Could you please try running this on chrome or edge also?

Chrome worked just fine today, so yeah probably just a local bug on my Brave browser. Thanks!
