### ISSUE TITLE
Out of memory issue

### ISSUE THREAD

**Issue by NagarajKamath** [pi-ra/beesy-issue-tracker#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

When my gmeet ends, beesy doesn't download the video automatically and also when I try to download it manually it says out of memory issue, but when I checked my task manager for cpu, ram and disk utilization, they are below 20% so no issue on system end. So seems to be issue from beesy end. Previously I had set the video format as webm and it was working fine when I set it to mp4, my issue started... please resolve this issue.

### Steps To Reproduce

When my gmeet ends, beesy doesn't download the video automatically and also when I try to download it manually it says out of memory issue, but when I checked my task manager for cpu, ram and disk utilization, they are below 20% so no issue on system end. So seems to be issue from beesy end. Previously I had set the video format as webm and it was working fine when I set it to mp4, my issue started... please resolve this issue.

### Environment including version

```Markdown
- Beesy: 0.0.14
- OS: windows 11
- Browser:chrome
- Media Player:vc
```

**Comment by piyu-sh** [comment]
Hi @NagarajKamath , could you please help share a few things: 

- how big was the recording in terms of time?
- could you please provide any screenshots of when it says, 'out of memory'?
- if it was working fine on webm, what was the need to change to mp4 ?
- also could you please try downloading the video using [steps in this comment](https://github.com/pi-ra/beesy-issue-tracker/issues/39#issuecomment-2137972550) and let us know how it goes ?

**Comment by NagarajKamath** [comment]
It was around 35 minutes for one video and 50min-1hour for another video. One s 212 mb and another is 1.36GB. Since some of the mobile isn't supporting webm, my users wee not able to access the video in webm format, So I switched to mp4. 
![Screenshot 2024-08-19 231304](https://github.com/user-attachments/assets/c21e817e-fa11-4f29-b172-37eeea1b8bf3)
![Screenshot 2024-08-19 231822](https://github.com/user-attachments/assets/5c7d5fd5-9559-444a-b4e2-f86e6e077f79)


I have attached screenshot. But Yes I was able to download the video using the console method you have shared. I have used this code:

(async function downloadFile(fileName){
  const opfsHandle = await navigator.storage.getDirectory()
  const recDir = await opfsHandle.getDirectoryHandle('beesy_recordings')
  const fileToDownloadHandle = await recDir.getFileHandle(fileName);
  const fileToDownload = await fileToDownloadHandle.getFile()
  const ab = await fileToDownload.arrayBuffer();
  const blb = new Blob([ab], {
    type: 'video/mp4',
  });
  chrome.downloads.download({url: URL.createObjectURL(blb), filename: fileName});
  
})('your_filename_here')





So issue is resolved as I was able to download bot the files.

**Comment by piyu-sh** [comment]
@NagarajKamath Glad that you were able to download both files !

Can you please try playing those videos if those are seekable in media player ? (For context , read [this comment](https://github.com/pi-ra/beesy-issue-tracker/issues/39#issuecomment-2142875710))

**Comment by NagarajKamath** [comment]
Yes they are working fine.
