### ISSUE TITLE
Join a Google Meet to enable recording

### ISSUE THREAD

**Issue by missrissippi** [pi-ra/beesy-issue-tracker#47]
### Is there an existing issue for this? (Please actually search the issues, instead of just checking the box)

- [X] I have searched the existing issues

### Bug description

It worked really well few days ago, but this morning I encountered a problem that is I can't record the meeting any longer. I have tried to refresh the page and made a new meeting, but it didn't work, it says "join a google meet to enable recording" but I'm already in the meeting.

![Screenshot (627)](https://github.com/user-attachments/assets/be771758-18a6-492f-b5b5-6ee7b67fce49)
![Screenshot (628)](https://github.com/user-attachments/assets/02a934ea-5d3a-4949-bd92-e84a91ae7717)

### Steps To Reproduce

1. Install the plugin using your work Google account.
2. Open Google Meet
3. Try to use the plugin to start recording.
4. You will see the message "Join a Google Meet to enable recording," even though you are already in the meeting, then you have encountered the issue.

### Environment including version

```Markdown
- Beesy: v0.0.14
- OS:Windows X
- Browser:Version 129.0.6668.101 (Official Build) (64-bit) (the latest)
- Media Player: -
```

**Comment by piyu-sh** [comment]
Hi @missrissippi , seems like Google changed something, we're looking into this.
Thanks.

**Comment by SagarBajpai** [comment]
@piyu-sh I'm facing the same issue. Not able to use Extension at all.

**Comment by piyu-sh** [comment]
@SagarBajpai we've already pushed a fix, it'll be live as soon as Google publishes the new version

**Comment by SqabyTechnologies** [comment]
same isssue device macos any idea?

**Comment by piyu-sh** [comment]
@SqabyTechnologies like we mentioned earlier, we've pushed the fix, waiting for Google to publish the new version.
We'll update this thread when the new version is live.

**Comment by SqabyTechnologies** [comment]
sounds good i like to know if there any possiblity of **adding openai or similar video transcribe api**

**Comment by piyu-sh** [comment]
@SqabyTechnologies could you please start a feature request for that and we can discuss there ? So this issue doesn't divert from its topic.

**Comment by piyu-sh** [comment]
Thanks for your patience everyone, this is taking more time than expected, but its still with Google, as soon as they publish the new version we'll update here.

**Comment by JADEN7777-h** [comment]
Please update here when the issues is fixed : ( forced to use other recorder tl;dv Team which isn't as great as beesy : ( Thanks !

**Comment by piyu-sh** [comment]
Hi @JADEN7777-h , really sorry for the inconvenience.
Its been 4 days since we pushed the fix, its just that Google is taking time to approve the new version and publish it.
We'll notify here as soon as we hear back.

**Comment by piyu-sh** [comment]
Hi everyone, new version is live.
Let us know if you still are not able to record

**Comment by missrissippi** [comment]
> Hi everyone, new version is live. Let us know if you still are not able to record

hey thank you so much, it works perfectly

**Comment by alexxdll** [comment]
Hi, still facing the same issue. weird that it works for missrissippi, do I need to update anything ?

**Comment by piyu-sh** [comment]
@alexxdll are you sure you're on v0.0.15 ?

**Comment by JADEN7777-h** [comment]
Hi There ! Yes finally I'm able to record now ! :) Thankiu so much ! @piyu-sh

**Comment by alexxdll** [comment]
@piyu-sh I was still on v0.0.14, now it works!! Thanks

**Comment by piyu-sh** [comment]
Closing this issue since the issue was fixed
