### ISSUE TITLE
Record Meeting option is disabled after joining the meet.

### ISSUE THREAD

**Issue by kushc2004** [pi-ra/beesy-issue-tracker#49]
### Is there an existing issue for this? (Please actually search the issues, instead of just checking the box)

- [X] I have searched the existing issues

### Bug description

The record meet option is disabled even after joining the meet. I am using Macbook Air M1.

### Steps To Reproduce

no

### Environment including version

```Markdown
- Beesy: 0.0.14
- OS: MacOS Sonama 14.6.1
- Browser: Arc, Chrome
- Media Player: none
```

### Attachments

no

**Comment by piyu-sh** [comment]
There's already an open issue for this going on, please search for existing issues.
