### ISSUE TITLE
<title>Unable to conduct recording despite I'm inside the Google Meet

### ISSUE THREAD

**Issue by JADEN7777-h** [pi-ra/beesy-issue-tracker#50]
### Is there an existing issue for this? (Please actually search the issues, instead of just checking the box)

- [X] I have searched the existing issues

### Bug description

I've no issue all this while until yesterday morning I couldn't record , and it stated "Join a google meet to enable recording" . I was already inside the Google Meet.. I'm unsure what's wrong. 

### Steps To Reproduce

1. Open Google Meet as usual 
2. Unable to start recording 

### Environment including version

```Markdown
Beesy: v0.0.11 (get version from: chrome://extensions/?id=eabicnldgjknbifdgmnieblkbnggfnde)
OS: macOS Ventura 13.4.1
Browser: Google Chrome v115.0.5790.170 (Official Build) (arm64)
Media Player: VLC v3.0.18 Vetinari (Intel 64bit)
```

**Comment by piyu-sh** [comment]
Hi @JADEN7777-h , there's an ognoing issue about this, please search for existing issues.
