### ISSUE TITLE
Since google meet update (With PIP feature) Beesy cannot record meetings anymore

### ISSUE THREAD

**Issue by leonardopmacedo** [pi-ra/beesy-issue-tracker#51]
### Is there an existing issue for this? (Please actually search the issues, instead of just checking the box)

- [X] I have searched the existing issues

### Bug description

Since a recent update (few days ago) of Google meet, i'm unable to record any meet session.

### Steps To Reproduce

Try to record any meeting with a google meet with the PIP feature available.

### Environment including version

```Markdown
- Beesy: 0.0.14
- OS: Windows 11
- Browser: Chrome  129.0.6668.101
- Media Player: Google Meet
```

### Attachments

![image](https://github.com/user-attachments/assets/21b0f580-21a1-4b9e-8043-5f9f5c3673c9)

**Comment by piyu-sh** [comment]
Hi @leonardopmacedo , sorry for the inconvenience, as you mentioned this is due to Google's recent update. 
There's already an ongoing issue open about this, please search for that existing issue to receive updates.
