### ISSUE TITLE
The extension is no more available on Chome Web Store

### ISSUE THREAD

**Issue by Surfer111** [pi-ra/beesy-issue-tracker#53]
### Is there an existing issue for this? (Please actually search the issues, instead of just checking the box)

- [X] I have searched the existing issues

### Bug description

The extension file installer is no more available on Chome Web Store

### Steps To Reproduce

1. press the button link Crome Web Store and you get this address:
https://chromewebstore.google.com/detail/error 

### Environment including version

```Markdown
- Beesy: last version
- OS: Edge
- Browser:
- Media Player:
```

**Comment by rahul-kurup** [comment]
Hey are you in the EU / US region by any chance?

**Comment by Surfer111** [comment]
I am in Italy

**Comment by Surfer111** [comment]
I am in Italy

 

 

Thank you for your efforts!

 

Da: rahul kurup ***@***.***> 
Inviato: venerdì 8 novembre 2024 18:04
A: pi-ra/beesy-issue-tracker ***@***.***>
Cc: Surfer111 ***@***.***>; Author ***@***.***>
Oggetto: Re: [pi-ra/beesy-issue-tracker] The extension is no more available on Chome Web Store (Issue #53)

 

Hey are you in the EU / US region by any chance?

**Comment by rahul-kurup** [comment]
Apologies for the late reply. 
We are NOT currently live in EU region, but would be available in future.

**Comment by Surfer111** [comment]
Thank you very much for your reply, there is no need to apologize for the delay. Thank you for everything you do for us.
How do I install your extension in Google Chrome?
Thank you.
________________________________

**Comment by rahul-kurup** [comment]
You can extract this [beesy_v0.0.15.crx.zip](https://github.com/user-attachments/files/17743037/beesy_v0.0.15.crx.zip) and install the `.crx` (Chrome extension file) by following the steps mentioned here https://superuser.com/a/252990
