### ISSUE TITLE
<title>Transcript in other languages

### ISSUE THREAD

**Issue by Surfer111** [pi-ra/beesy-issue-tracker#54]
### Is there an existing request for this?

- [X] I have searched the existing issues

### Feature description

The extension works very well on both Google Chrome and Edge. Thanks and compliments!
The transcription for now is only in English .... it would not be bad if it is possible to implement it in other languages ​​​​maybe in Italian. Thank you again

**Comment by piyu-sh** [comment]
Hi @Surfer111, thanks for using our extension.
About your suggestion, I think having transcripts in Italian (or any other language) should already be possible.

You can change the language from the option in screenshot when captions are enabled, see on bottom left, where it says 'English(India)', if you click on it, you should be able to change it to any language Google Meet supports.
![image](https://github.com/user-attachments/assets/17aa816a-e68e-4956-9721-1d2a76b04e6f)

Also if you want you can go to Google Meet settiings and change transcript language from below option
![image](https://github.com/user-attachments/assets/3dc75888-bd1e-4895-b469-c80807b7dcf7)

**Comment by Surfer111** [comment]
Thanks for your work.

You are right!

I tried your suggestions right away and everything works as you explained.

 

Thank you very much again!

👏👏👏

 

Ermanno 

 ***@***.***> ***@***.***  

 

Da: Piyush ***@***.***> 
Inviato: giovedì 19 dicembre 2024 18:15
A: pi-ra/beesy-issue-tracker ***@***.***>
Cc: Surfer111 ***@***.***>; Mention ***@***.***>
Oggetto: Re: [pi-ra/beesy-issue-tracker] <title>Transcript in other languages (Issue #54)

 

Hi @Surfer111 <https://github.com/Surfer111> , thanks for using our extension.
About your suggestion, I think having transcripts in Italian (or any other language) should already be possible.

You can change the language from the option in screenshot when captions are enabled, see on bottom left, where it says 'English(India)', if you click on it, you should be able to change it to any language Google Meet supports.
image.png (view on web) <https://github.com/user-attachments/assets/17aa816a-e68e-4956-9721-1d2a76b04e6f> 

Also if you want you can go to Google Meet settiings and change transcript language from below option
image.png (view on web) <https://github.com/user-attachments/assets/3dc75888-bd1e-4895-b469-c80807b7dcf7>
